### ISSUE TITLE
Issue in checking the koans

### ISSUE THREAD

**Issue by Inbar312** [jletroui/FrcJavaKoans#40]
Every time I run the program after solving/trying to solve a koan, it took my progress bar a few koans back and displayed like there were bugs in koans I already solved. I managed to move on after a changing small things in my earlier koans solutions, but every new koan since then it would happen again.
In the last one I lost hope and stopped running it over and over again, after it kept going back to Not7! game
[java copy - issue with checking koans.zip](https://github.com/jletroui/FrcJavaKoans/files/12148078/java.copy.-.issue.with.checking.koans.zip)

**Comment by jletroui** [comment]
@Inbar312 you've hit https://github.com/jletroui/FrcJavaKoans/issues/25. When running your koans, I can see this:

```
The master sensed the harmony dissolving when planning to answer y, y, n, y, y, and n.


Console for not7Gamev1():
---------

Player 1, it's your turn!

You threw 5 and 2.
Oh no, Not 7! You loose!


Player 2, it's your turn!

You threw 3 and 5.
Your result so far: 8.
Do you want to throw again [y/n]?
y
You threw 6 and 1.
Oh no, Not 7! You loose!



---------

Ok: displayed 'Player 1, it's your turn!' in the console.
Ok: displayed an empty line in the console.
Ok: displayed 'You threw 5 and 2.' in the console.
Ok: displayed 'Oh no, Not 7! You loose!' in the console.
Ok: displayed an empty line in the console.
Expected to see 'Player 2, it's your turn!' in the console, but did not see it!
```

The last line is explaining what should happen, but is not happening. The tricky part is that this is not a problem in `not7Gamev1()` but in `gameRoundv5`.

I can understand the high level of confusion, so I will probably modify the way random numbers are generated so that once a koan pass, it really is passing in all situations.

Thanks so much for helping me understand your issue!

**Comment by jletroui** [comment]
@Inbar312 problem fixed. You can redownload the zip file, replace its files in the `src/main/java/koans/english` directory by yours.

The koan you did not solve completely should appear with the right message, allowing you to continue without confusing messages.

**Comment by Inbar312** [comment]
That's great! Thank you so much for your help!
